apiVersion: apps/v1
kind: deployment
metadata:
  name: Deployment1-test
spec:
  replicas: 2
  selectors:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app 
    spec:
      containers: 
        - name: Deployment-C1
          image: nginx:latest
          ports:
            - containerPort: 80 
      
    
  