apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers: 
        - name: deployment-c
          image: nginx:latest
          ports:
            - containerPort: 80 
      
    
  