apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
     spec:
       containers:
         - name: nginx-container
           image: nginx
           ports:
             - containerPort: 80
           env:
             - name: TITLE
               value: "NGINX APP1"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
     targetPort: 80
     protocol: TCP
  selector:
    app: nginx
