apiVersion: apps/v1  # Correct API version for ReplicaSet
kind: ReplicaSet     # Correct kind without hyphen
metadata:
  name: replica-set1
spec:
  replicas: 3
  selector:
    matchLabels:
     app: my-app
  template:
    metadata:
     labels:
      app: my-app
    spec:
      containers: 
      - name: replica-container
        image: clahandevops/flower-img:latest

        
  
  